// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGA.Data;

#nullable disable

namespace SGA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228221734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGA.Models.AlertaIgnorada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveUnica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaIgnorada")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AlertasIgnoradas");
                });

            modelBuilder.Entity("SGA.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AsistenciaId"));

                    b.Property<bool>("EstaPresente")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("SGA.Models.CierreCajaDiario", b =>
                {
                    b.Property<int>("CierreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CierreId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("SaldoNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGastos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalHuevosVendidos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("CierreId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CierresCajaDiarios");
                });

            modelBuilder.Entity("SGA.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("DNI")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Deuda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DireccionLocal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCumpleanios")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MetodoPagoPreferido")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PrecioEspecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiereFactura")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UltimaCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VentasTotales")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClienteId");

                    b.HasIndex("DNI")
                        .IsUnique()
                        .HasFilter("\"DNI\" IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SGA.Models.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompraId"));

                    b.Property<string>("ComprobantePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("CompraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("SGA.Models.ContenidoSilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoPorUnidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SiloId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SiloId");

                    b.ToTable("ContenidosSilos");
                });

            modelBuilder.Entity("SGA.Models.DetalleCompra", b =>
                {
                    b.Property<int>("DetalleCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleCompraId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompraId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetalleCompraId");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesCompra");
                });

            modelBuilder.Entity("SGA.Models.DetallePedido", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DetalleId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("SGA.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("DetalleId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("SGA.Models.EventoGalpon", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GalponId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("EventoId");

                    b.HasIndex("GalponId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EventosGalpon");
                });

            modelBuilder.Entity("SGA.Models.EventoMortalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("EventosMortalidad");
                });

            modelBuilder.Entity("SGA.Models.Falta", b =>
                {
                    b.Property<int>("FaltaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FaltaId"));

                    b.Property<bool>("EsJustificada")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("FaltaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Faltas");
                });

            modelBuilder.Entity("SGA.Models.Galpon", b =>
                {
                    b.Property<int>("GalponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GalponId"));

                    b.Property<int>("CantidadAves")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaBajaEstimada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioCompraAve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("GalponId");

                    b.ToTable("Galpones");
                });

            modelBuilder.Entity("SGA.Models.GastoVehiculo", b =>
                {
                    b.Property<int>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GastoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LitrosCombustible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("GastoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("GastosVehiculos");
                });

            modelBuilder.Entity("SGA.Models.HistorialAccion", b =>
                {
                    b.Property<int>("HistorialAccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialAccionId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalles")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .HasColumnType("text");

                    b.Property<string>("EntidadId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("HistorialAccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialAcciones");
                });

            modelBuilder.Entity("SGA.Models.ItemInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId");

                    b.ToTable("ItemsInventario");
                });

            modelBuilder.Entity("SGA.Models.LoteAve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoAve")
                        .HasColumnType("integer");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId");

                    b.ToTable("LotesAves");
                });

            modelBuilder.Entity("SGA.Models.MovimientoStock", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("MovimientoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("SGA.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificacionId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("NotificacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SGA.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PagoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SGA.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PedidoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaPagado")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("ViajeId")
                        .HasColumnType("integer");

                    b.HasKey("PedidoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ViajeId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SGA.Models.Produccion", b =>
                {
                    b.Property<int>("ProduccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProduccionId"));

                    b.Property<decimal>("CantidadKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("SiloDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ProduccionId");

                    b.HasIndex("SiloDestinoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Producciones");
                });

            modelBuilder.Entity("SGA.Models.ProduccionIngrediente", b =>
                {
                    b.Property<int>("ProduccionIngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProduccionIngredienteId"));

                    b.Property<decimal>("CantidadKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduccionId")
                        .HasColumnType("integer");

                    b.Property<int>("SiloId")
                        .HasColumnType("integer");

                    b.HasKey("ProduccionIngredienteId");

                    b.HasIndex("ProduccionId");

                    b.HasIndex("SiloId");

                    b.ToTable("ProduccionIngredientes");
                });

            modelBuilder.Entity("SGA.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoId"));

                    b.Property<int?>("Color")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoUltimaCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EsHuevo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioMaximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockMinimoAlerta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Tamano")
                        .HasColumnType("integer");

                    b.Property<int>("TipoProducto")
                        .HasColumnType("integer");

                    b.Property<decimal>("UltimoMargen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadDeMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UnidadesPorBulto")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SGA.Models.Silo", b =>
                {
                    b.Property<int>("SiloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiloId"));

                    b.Property<decimal>("CantidadActualKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapacidadKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioPromedioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("SiloId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Silos");
                });

            modelBuilder.Entity("SGA.Models.StockVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Cantidad");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductoId");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UltimaActualizacion");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("VehiculoId");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("StockVehiculos");
                });

            modelBuilder.Entity("SGA.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("SGA.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SGA.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.Property<decimal>("CapacidadCarga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumoPromedioLts100Km")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EnRuta")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoCubiertas")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ID_Chofer_Asignado")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Chofer_Asignado");

                    b.Property<decimal>("Kilometraje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KilometrajeProximoCambioAceite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoAceite")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UltimoCambioAceite")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VehiculoId");

                    b.HasIndex("ID_Chofer_Asignado");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("SGA.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VentaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DescuentoMonto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ViajeId")
                        .HasColumnType("integer");

                    b.HasKey("VentaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("ViajeId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SGA.Models.Viaje", b =>
                {
                    b.Property<int>("ViajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ViajeId"));

                    b.Property<int?>("AcompananteId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoferId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaRegreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("ViajeId");

                    b.HasIndex("AcompananteId");

                    b.HasIndex("ChoferId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("SGA.Models.Asistencia", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Models.CierreCajaDiario", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Models.Compra", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Models.ContenidoSilo", b =>
                {
                    b.HasOne("SGA.Models.Silo", "Silo")
                        .WithMany()
                        .HasForeignKey("SiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Silo");
                });

            modelBuilder.Entity("SGA.Models.DetalleCompra", b =>
                {
                    b.HasOne("SGA.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SGA.Models.DetallePedido", b =>
                {
                    b.HasOne("SGA.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SGA.Models.DetalleVenta", b =>
                {
                    b.HasOne("SGA.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SGA.Models.EventoGalpon", b =>
                {
                    b.HasOne("SGA.Models.Galpon", "Galpon")
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Galpon");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Models.EventoMortalidad", b =>
                {
                    b.HasOne("SGA.Models.LoteAve", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("SGA.Models.Falta", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Models.GastoVehiculo", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.HasOne("SGA.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Empleado");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SGA.Models.HistorialAccion", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Models.ItemInventario", b =>
                {
                    b.HasOne("SGA.Models.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SGA.Models.LoteAve", b =>
                {
                    b.HasOne("SGA.Models.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SGA.Models.MovimientoStock", b =>
                {
                    b.HasOne("SGA.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SGA.Models.Notificacion", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Models.Pago", b =>
                {
                    b.HasOne("SGA.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SGA.Models.Pedido", b =>
                {
                    b.HasOne("SGA.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Viaje", "Viaje")
                        .WithMany()
                        .HasForeignKey("ViajeId");

                    b.Navigation("Cliente");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("SGA.Models.Produccion", b =>
                {
                    b.HasOne("SGA.Models.Silo", "SiloDestino")
                        .WithMany()
                        .HasForeignKey("SiloDestinoId");

                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiloDestino");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Models.ProduccionIngrediente", b =>
                {
                    b.HasOne("SGA.Models.Produccion", "Produccion")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Silo", "Silo")
                        .WithMany()
                        .HasForeignKey("SiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produccion");

                    b.Navigation("Silo");
                });

            modelBuilder.Entity("SGA.Models.Silo", b =>
                {
                    b.HasOne("SGA.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SGA.Models.StockVehiculo", b =>
                {
                    b.HasOne("SGA.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SGA.Models.Vehiculo", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "ChoferAsignado")
                        .WithMany()
                        .HasForeignKey("ID_Chofer_Asignado");

                    b.Navigation("ChoferAsignado");
                });

            modelBuilder.Entity("SGA.Models.Venta", b =>
                {
                    b.HasOne("SGA.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Viaje", "Viaje")
                        .WithMany()
                        .HasForeignKey("ViajeId");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("SGA.Models.Viaje", b =>
                {
                    b.HasOne("SGA.Models.Usuario", "Acompanante")
                        .WithMany()
                        .HasForeignKey("AcompananteId");

                    b.HasOne("SGA.Models.Usuario", "Chofer")
                        .WithMany()
                        .HasForeignKey("ChoferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanante");

                    b.Navigation("Chofer");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SGA.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SGA.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SGA.Models.Produccion", b =>
                {
                    b.Navigation("Ingredientes");
                });

            modelBuilder.Entity("SGA.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
